### ISSUE TITLE
storybook start with lots of warnings

### ISSUE THREAD

**Issue by gabimor** [nuxt-community/storybook#188] opened 2020-11-30 10:06 UTC
### Version
@nuxtjs/storybook: 3.2
nuxt: 2.14.7
language: Typescript

### Steps to reproduce
Run `nuxt storybook`

### What is Expected?
Storybook starts without errors, also the progess bar shows correctly

### What is actually happening?
Storybook starts but shows a lot of warnings of this style:
```
● Client █████████████████████████ sealing (70%)


Neither '~/mixins/OnProductPushStateMixin.vue.vue' nor '~/mixins/OnProductPushStateMixin.vue.js(x)' or '~/mixins/OnProductPushStateMixin.vue/index.js(x)' or '~/mixins/OnProductPushStateMixin.vue/index.ts(x)' could be found in '/Users/gabimor/Code/withcon

● Client █████████████████████████ after chunk graph (71%)


Neither '~/mixins/OnProductPushStateMixin.vue.vue' nor '~/mixins/OnProductPushStateMixin.vue.js(x)' or '~/mixins/OnProductPushStateMixin.vue/index.js(x)' or '~/mixins/OnProductPushStateMixin.vue/index.ts(x)' could be found in '/Users/gabimor/Code/withcon

● Client █████████████████████████ advanced chunk optimization (77%) RuntimeChunkPlugin


Neither '~/mixins/OnProductPushStateMixin.vue.vue' nor '~/mixins/OnProductPushStateMixin.vue.js(x)' or '~/mixins/OnProductPushStateMixin.vue/index.js(x)' or '~/mixins/OnProductPushStateMixin.vue/index.ts(x)' could be found in '/Users/gabimor/Code/withcon

● Client █████████████████████████ chunk reviving (85%)
```

**Comment by farnabaz** [comment] 2020-11-30 16:09
Close, because it is a duplicate of #152 and will fill in #184.

**Closed by farnabaz** 2020-11-30 16:09 UTC
Labels: bug
