### ISSUE TITLE
Invalid path resolution

### ISSUE THREAD

**Issue by Armaldio** [nuxt-community/storybook#102] opened 2020-08-24 09:52 UTC
I *assume* on Windows path are not resolved correctly

- CLI
![image](https://user-images.githubusercontent.com/3089715/91030639-c43d6300-e5ff-11ea-8f56-3f3d58483b9c.png)
- Generated files
![image](https://user-images.githubusercontent.com/3089715/91030763-f2bb3e00-e5ff-11ea-8ee0-772276f16577.png)
(backslashes are not escaped which cause the path to not be resolved correctly)

I also manually set srcDir inside the config file
![image](https://user-images.githubusercontent.com/3089715/91030999-3f067e00-e600-11ea-9e17-544158653d22.png)

### Version
@nuxtjs/storybook: 2.1.0 
nuxt: 2.14.3 

### Reproduction Link
https://codesandbox.io/s/cranky-cookies-y5if8?file=/src/components/test.stories.js

Note: This sandbox just show my architecture as the error seems related to the OS & path escaping and I assume sandbox runs on linux

### Steps to reproduce

Run `yarn nuxt storybook`

### What is Expected?

The app should compile

### What is actually happening?

![image](https://user-images.githubusercontent.com/3089715/91030597-b556b080-e5ff-11ea-8dd5-add97b704806.png)

**Comment by farnabaz** [comment] 2020-08-24 10:38
I believe this fixed in https://github.com/nuxt-community/storybook/pull/93.  
@lihbr am I right about this?  

New version (v2.2.0) will be out in a couple of days

**Comment by lihbr** [comment] 2020-08-24 10:49
Yup that's this very one 🙂

**Comment by Armaldio** [comment] 2020-08-24 10:58
It's not released yet, so 🙂 ?

**Comment by farnabaz** [comment] 2020-08-24 11:02
> It's not released yet, so 🙂 ?

Not yet, will release in 2.2.0 within a day

**Comment by farnabaz** [comment] 2020-08-31 18:57
[v2.2.0](https://github.com/nuxt-community/storybook/releases/tag/v2.2.0) is out :)

**Comment by AndrewBogdanovTSS** [comment] 2020-09-01 10:52
It's still happening in 2.2.0. Please, reopen

**Comment by farnabaz** [comment] 2020-09-01 11:17
@AndrewBogdanovTSS Could you provide a reproduction project? I already tested Armaldio's project in 2.2.0 and it works as expected

**Comment by lihbr** [comment] 2020-09-01 13:38
Tested on my side with `2.2.0` and works as expected 🤔 are you sure you're experiencing the same issue as described above? Path should now be final normalized: https://github.com/nuxt-community/storybook/blob/master/src/index.ts#L180

**Comment by AndrewBogdanovTSS** [comment] 2020-09-01 15:48
I can't replicate this issue on the clean nuxt instance. But locally I get this error: 
```
ERROR in ./.nuxt-storybook/storybook/storybook-init-framework-entry.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
ENOENT: no such file or directory, open 'H:\Projects\Wonder\frontend\.nuxt-storybook\storybook\storybo
ok-init-framework-entry.js'
    at PoolWorker.fromErrorObj (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool
.js:262:12)
    at H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool.js:204:29
    at mapSeries (H:\Projects\Wonder\frontend\node_modules\neo-async\async.js:3625:14)
    at PoolWorker.onWorkerMessage (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerP
ool.js:170:35)
    at H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool.js:152:14
    at Socket.onChunk (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\readBuffer.js:36:9)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Socket.Readable.read (_stream_readable.js:514:10)
    at Socket.read (net.js:625:39)
    at flow (_stream_readable.js:987:34)
    at emitReadable_ (_stream_readable.js:578:3)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
 @ multi ./.nuxt-storybook/client.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./
node_modules/@storybook/core/dist/server/preview/globals.js ./.nuxt-storybook/storybook/storybook-init
-framework-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-othe
r-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./.
nuxt-storybook/storybook/preview.js-generated-config-entry.js ./.nuxt-storybook/storybook/generated-st
ories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[3]

ERROR in ./.nuxt-storybook/storybook/preview.js-generated-config-entry.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 1)
ENOENT: no such file or directory, open 'H:\Projects\Wonder\frontend\.nuxt-storybook\storybook\preview
.js-generated-config-entry.js'
    at PoolWorker.fromErrorObj (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool
.js:262:12)
    at H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool.js:204:29
    at mapSeries (H:\Projects\Wonder\frontend\node_modules\neo-async\async.js:3625:14)
    at PoolWorker.onWorkerMessage (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerP
ool.js:170:35)
    at H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool.js:152:14
    at Socket.onChunk (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\readBuffer.js:36:9)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Socket.Readable.read (_stream_readable.js:514:10)
    at Socket.read (net.js:625:39)
    at flow (_stream_readable.js:987:34)
    at emitReadable_ (_stream_readable.js:578:3)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
 @ multi ./.nuxt-storybook/client.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./
node_modules/@storybook/core/dist/server/preview/globals.js ./.nuxt-storybook/storybook/storybook-init
-framework-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-othe
r-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./.
nuxt-storybook/storybook/preview.js-generated-config-entry.js ./.nuxt-storybook/storybook/generated-st
ories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[6]

ERROR in ./.nuxt-storybook/storybook/generated-stories-entry.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 2)
ENOENT: no such file or directory, open 'H:\Projects\Wonder\frontend\.nuxt-storybook\storybook\generat
ed-stories-entry.js'
    at PoolWorker.fromErrorObj (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool
.js:262:12)
    at H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool.js:204:29
    at mapSeries (H:\Projects\Wonder\frontend\node_modules\neo-async\async.js:3625:14)
    at PoolWorker.onWorkerMessage (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerP
ool.js:170:35)
    at H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\WorkerPool.js:152:14
    at Socket.onChunk (H:\Projects\Wonder\frontend\node_modules\thread-loader\dist\readBuffer.js:36:9)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Socket.Readable.read (_stream_readable.js:514:10)
    at Socket.read (net.js:625:39)
    at flow (_stream_readable.js:987:34)
    at emitReadable_ (_stream_readable.js:578:3)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
 @ multi ./.nuxt-storybook/client.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./
node_modules/@storybook/core/dist/server/preview/globals.js ./.nuxt-storybook/storybook/storybook-init
-framework-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addDecorator.js-generated-othe
r-entry.js ./node_modules/@storybook/addon-actions/dist/preset/addArgs.js-generated-other-entry.js ./.
nuxt-storybook/storybook/preview.js-generated-config-entry.js ./.nuxt-storybook/storybook/generated-st
ories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined main[7]
```
It might not be related to this specific problem with path though...so maybe a new issue should be created

**Comment by lihbr** [comment] 2020-09-01 15:51
Indeed it doesn't look like the same issue, it'll be awesome if you can open another issue providing these logs & your Nuxt config 🙂

**Comment by AndrewBogdanovTSS** [comment] 2020-09-01 15:53
@lihbr yeah, will try to replicate this it in the codesandbox later today. Just found out that its OS independent

**Comment by farnabaz** [comment] 2020-09-27 17:21
@AndrewBogdanovTSS any news on this?

**Comment by adamskeeled** [comment] 2020-10-07 09:15
Any updates on this? Also happening to me

**Comment by lihbr** [comment] 2020-10-07 09:35
Have you tried to delete your `package-lock.json` or `yarn.lock` and then install everything again? I had some odd issues like the above few times and this helped because Storybook installs a lot of stuff which can lead to the package manager messing up sometimes 🤔

**Comment by adamskeeled** [comment] 2020-10-07 09:43
I think I found the issue. On a clean nuxt project I installed the storybook module, and after a few tests, found out that having the build option `parallel: true` causes this issue of `no such file or directory /path/to/project/.nuxt-storybook\storybook\storybo
ok-init-framework-entry.js`

**Comment by lihbr** [comment] 2020-10-07 10:07
Nice catch 🤔 @farnabaz might be interested in investigating it more or perhaps already have an idea about it ☺️

**Comment by farnabaz** [comment] 2020-10-07 14:36
There is an [unresolved issue](https://github.com/storybookjs/storybook/issues/9515) in Storybook about using `thread-loader`.  I guest our best solution for now is to disable `parallel` for storybook build.

**Closed** 2020-10-07 15:18 UTC
Labels: bug

**Comment by AndrewBogdanovTSS** [comment] 2020-10-08 15:01
Sorry for the late reply. Once I've upgraded to v.3.0.0 the error is gone even when using `parallel` option. 👍
